// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvvsuhzvcjnuvkteygpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2dnN1aHp2Y2pudXZrdGV5Z3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTAzNDgsImV4cCI6MjA3MTU2NjM0OH0.-Z4Bk4AQE5S9sU5_lhCynI1Y6qVNRidhAlneU2Cd3_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});